# Generated by Django 3.2.9 on 2022-08-27 21:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('productId', models.CharField(editable=False, max_length=50)),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Hero')),
                ('partNo', models.CharField(blank=True, max_length=120, verbose_name='Part No')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='Brand')),
                ('typeOfProduct', models.CharField(choices=[('Hero', 'Hero'), ('Battery', 'Battery'), ('Tyre', 'Tyre')], default='Select Type', max_length=255, verbose_name='Product Type')),
                ('capacity', models.CharField(blank=True, default=0.0, help_text='If Product is Battery Please fill Capacity, otherwise Leave Blank', max_length=5, verbose_name='Battery Capacity')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('sku', models.CharField(blank=True, max_length=120, verbose_name='SKU')),
                ('mainImage', models.ImageField(blank=True, default='default.jpg', upload_to='products_images/{product.typeOfProduct}', verbose_name='Hero Image')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, help_text='Image size should be 1920 x 1280px', upload_to='products_images/{product.typeOfProduct}', verbose_name='Set Image (1920 x 1280px)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Select Product Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HT',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ManyToManyField(related_name='product_ht', to='products.Product', verbose_name='HT')),
            ],
            options={
                'verbose_name': 'Hero Tyre',
                'verbose_name_plural': 'HTs',
                'db_table': 'hts',
            },
        ),
        migrations.CreateModel(
            name='HBT',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ManyToManyField(related_name='product_hbt', to='products.Product', verbose_name='HBT')),
            ],
            options={
                'verbose_name': 'Hero Battery Tyre',
                'verbose_name_plural': 'HBTs',
                'db_table': 'hbts',
            },
        ),
        migrations.CreateModel(
            name='HB',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ManyToManyField(related_name='product_hb', to='products.Product', verbose_name='HB')),
            ],
            options={
                'verbose_name': 'Hero Battery',
                'verbose_name_plural': 'HBs',
                'db_table': 'hbs',
            },
        ),
    ]
