# Generated by Django 3.2.9 on 2022-08-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Product Name'),
        ),
    ]
