# Generated by Django 3.2.9 on 2022-08-27 22:37

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adhaar_certificate',
            field=models.FileField(blank=True, upload_to=apps.profiles.models.user_directory_path, verbose_name='Adhaar Certificate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gst_certificate',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='GST Certificate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan_certificate',
            field=models.FileField(blank=True, upload_to=apps.profiles.models.user_directory_path, verbose_name='PAN Card'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='security_cheque',
            field=models.FileField(blank=True, upload_to=apps.profiles.models.user_directory_path, verbose_name='Security Cheque'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='visiting_card',
            field=models.FileField(blank=True, upload_to=apps.profiles.models.user_directory_path, verbose_name='Visiting Card'),
        ),
    ]
