# Generated by Django 3.2.9 on 2022-08-27 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import yantrayugBackend.dependancies


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dispatchOrderID', models.CharField(editable=False, max_length=50)),
                ('entryDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Time')),
                ('pickList', models.PositiveIntegerField(blank=True, default=0, verbose_name='Pick List')),
                ('billStatus', models.CharField(choices=[('Complete', 'Complete'), ('In Complete', 'In Complete')], default='Select Status', max_length=255, verbose_name='Bill Status')),
                ('deliveryDate', models.DateTimeField(verbose_name='Enter Delivery Date')),
                ('dispatchStatus', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Hold', 'Hold'), ('Cancel', 'Cancel')], default='Select Status', max_length=120, verbose_name='Dispatch Status')),
                ('recievedStatus', models.CharField(choices=[('Complete', 'Complete'), ('In Complete', 'In Complete')], default='Select Status', max_length=120, verbose_name='Recieved Status')),
                ('recievedImage', models.FileField(blank=True, upload_to=yantrayugBackend.dependancies.path_and_rename, verbose_name='Upload Recieved Image')),
                ('payment_method', models.CharField(blank=True, choices=[('Cash On Delivery', 'Cash On Delivery'), ('Online Mode', 'Online Mode'), ('Cheque', 'Cheque')], default='Select Payment Method', max_length=100, null=True, verbose_name='Payment Mode')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='Remark')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deliveredBoy', models.ForeignKey(default='Select Delivery Person', on_delete=django.db.models.deletion.PROTECT, related_name='delivered_by', to='profiles.salesman', verbose_name='Delivered By')),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
                'db_table': 'dispatches',
            },
        ),
        migrations.CreateModel(
            name='RecievedReciept',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash On Delivery', 'Cash On Delivery'), ('Online Mode', 'Online Mode'), ('Cheque', 'Cheque')], default='Select Payment Method', max_length=100, null=True, verbose_name='Payment Mode')),
                ('uploadReciept', models.FileField(blank=True, upload_to=yantrayugBackend.dependancies.path_and_rename, verbose_name='Upload Recieved Image/File')),
                ('recivedStatus', models.CharField(choices=[('Complete', 'Complete'), ('In Complete', 'In Complete')], default='Select Status', max_length=120, verbose_name='Recieved Status')),
                ('locationLink', models.CharField(blank=True, max_length=64, null=True, verbose_name='Google Map Link')),
                ('latitude', models.FloatField(blank=True, default=19.214, verbose_name='Set Latitude')),
                ('longitude', models.FloatField(blank=True, default=19.214, verbose_name='Set Longitude')),
                ('area_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Area Name')),
                ('landmark', models.CharField(blank=True, max_length=64, null=True, verbose_name='Landmark')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='Remark')),
                ('ratings', models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor'), ('BAD', 'BAD')], max_length=255, verbose_name='Ratings')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dispatch.dispatch', verbose_name='Dispatch ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoiceNo', models.CharField(editable=False, max_length=120, verbose_name='Invoice No')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_dispatch', to='profiles.customer', verbose_name='Party Name')),
                ('product', models.ManyToManyField(related_name='product_invoice', to='products.Product', verbose_name='Select Product')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
            },
        ),
        migrations.AddField(
            model_name='dispatch',
            name='invoiceNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_dispatch', to='dispatch.invoice', verbose_name='Invoice No'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pickerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picker_name', to=settings.AUTH_USER_MODEL, verbose_name='Picker Name'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesman_custmrdispatch', to='profiles.salesman', verbose_name='Salesman Name'),
        ),
    ]
