# Generated by Django 3.2.9 on 2022-08-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiceNo',
            field=models.CharField(max_length=120, verbose_name='Invoice No'),
        ),
    ]
