# Generated by Django 3.2.9 on 2022-08-27 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220828_0407'),
        ('dispatch', '0002_alter_invoice_invoiceno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='billStatus',
            field=models.CharField(choices=[('Complete', 'Complete'), ('In Complete', 'In Complete')], default='Select', max_length=255, verbose_name='Bill Status'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='deliveredBoy',
            field=models.ForeignKey(blank=True, default='Select Delivery Person', on_delete=django.db.models.deletion.PROTECT, related_name='delivered_by', to='profiles.salesman', verbose_name='Delivered By'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='deliveryDate',
            field=models.DateTimeField(blank=True, verbose_name='Enter Delivery Date'),
        ),
    ]
