# Generated by Django 3.2.9 on 2022-08-27 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220828_0407'),
        ('dispatch', '0003_auto_20220828_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='billStatus',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Select', max_length=255, verbose_name='Bill Status'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='deliveredBoy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_by', to='profiles.salesman', verbose_name='Delivered By'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='deliveryDate',
            field=models.DateTimeField(verbose_name='Enter Delivery Date'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Hold', 'Hold'), ('Cancel', 'Cancel')], default='Select Status', max_length=120, verbose_name='Dispatch Status'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='recievedStatus',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Select Status', max_length=120, verbose_name='Recieved Status'),
        ),
        migrations.AlterField(
            model_name='recievedreciept',
            name='recivedStatus',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Select Status', max_length=120, verbose_name='Recieved Status'),
        ),
    ]
