# Generated by Django 3.2.9 on 2022-08-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_auto_20220828_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
